= Containers

In this repo https://github.com/containers/buildah[buildah] and https://github.com/containers/podman[podman] is
used to create

- Images
- Pods
- Containers

== Fedora

=== Fedora Updated (jarrydk/fedora-updates:36)

Based on `fedora:36` create an updated image.

*Build the images*
[source,bash]
----
cd fedora/fedora-updated
./buils_images.sh
----

=== jdk11 on Fedora (jarrydk/fedora-adoptium-openjdk:11)

Based on `fedora:36` or `jarrydk/fedora-updates:36` it will add `jdk-11` to the image.

*Build the images*
[source,bash]
----
cd fedora/jdk11
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    jarrydk/fedora-adoptium-openjdk:11 \
    java -version
----

=== jdk17 on Fedora (jarrydk/fedora-adoptium-openjdk:17)

Based on `fedora:36` or `jarrydk/fedora-updates:36` it will add `jdk-17` to the image.

*Build the images*
[source,bash]
----
cd fedora/jdk17
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    jarrydk/fedora-adoptium-openjdk:17 \
    java -version
----

=== jdk19 on Fedora (jarrydk/fedora-adoptium-openjdk:19)

Based on `fedora:36` or `jarrydk/fedora-updates:36` it will add `jdk-19` to the image.

*Build the images*
[source,bash]
----
cd fedora/jdk19
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    jarrydk/fedora-adoptium-openjdk:19 \
    java -version
----

=== wildfly-26.1.2.Final on Fedora (jarrydk/fedora-wildfly:26.1.2.Final)

Based on jarrydk/fedora-adoptium-openjdk:17 it will add Wildfly 26.1.2.Final

*Build the images*
[source,bash]
----
cd fedora/wildfly-26.1.2.Final
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    -p 8080:8080 \
    jarrydk/fedora-wildfly:26.1.2.Final
----

=== Kafka on Fedora

Based on `fedora:36`, `jarrydk/fedora-updates:36` or `jarrydk/fedora-adoptium-openjdk:17` it will add `Kafka` to the image.

link:fedora/kafka/README.adoc[fedora/kafka/README.adoc]

https://hub.docker.com/r/jarrydk/fedora-kafka[hub.docker.com/r/jarrydk/fedora-kafka]

=== Kafka ZooKeeper on Fedora

Based on `fedora:36`, `jarrydk/fedora-updates:35` or `jarrydk/fedora-adoptium-openjdk:17` it will add `Kafka ZooKeeper` to the image.


link:fedora/kafka-zookeeper/README.adoc[fedora/kafka-zookeeper/README.adoc]

https://hub.docker.com/r/jarrydk/fedora-kafka-zookeeper[hub.docker.com/r/jarrydk/fedora-kafka-zookeeper]


OpenJdk 17 will be located in the folder `/opt/java/openjdk-17`

== CentOS

=== jdk17 on CentOS (jarrydk/centos-adoptium-openjdk:17)

Based on `centos:latest` it will add `jdk-17` to the image.

*Build the images*
[source,bash]
----
cd centos/jdk17
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    jarrydk/centos-adoptium-openjdk:17 \
    java -version
----

=== wildfly-26.1.2.Final on CentOS (jarrydk/centos-wildfly:26.1.2.Final)

Based on jarrydk/centos-openjdk:17 it will add Wildfly 26.1.2.Final

*Build the images*
[source,bash]
----
cd centos/wildfly-26.1.2.Final
./buils_images.sh
----

*Test the images*
[source,bash]
----
podman run -it --rm=true \
    -p 8080:8080 \
    jarrydk/centos-wildfly:26.1.2.Final
----

== Local registry

We might like to run a local registry.

[source,bash]
----
podman run -it -p 5000:5000 --name registry registry:2
----

My local ip is `192.168.1.36`.

[source,bash]
----
podman push localhost/jarrydk/fedora-adoptium-openjdk:17 192.168.1.36:5000/jarrydk/fedora-adoptium-openjdk:17
----

If we like to get the images `jarrydk/fedora-adoptium-openjdk:17` in an insecure way from `192.168.1.36` - 
we need to add some lines to `/etc/containers/registries.conf`

[source,bash]
----
echo '' >> /etc/containers/registries.conf
echo '# Manual update' >> /etc/containers/registries.conf
echo '[[registry]]' >> /etc/containers/registries.conf
echo 'prefix = "192.168.1.36:5000"' >> /etc/containers/registries.conf
echo 'location = "192.168.1.36:5000/jarrydk"' >> /etc/containers/registries.conf
echo 'insecure = true' >> /etc/containers/registries.conf
----

== Tools

* https://github.com/containers/buildah[buildah]
* https://github.com/containers/podman[podman]

== Links

* https://www.redhat.com/sysadmin/compose-podman-pods[Moving from docker-compose to Podman pods]
* https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods/[Podman: Managing pods and containers in a local container runtime]
* https://fedoramagazine.org/manage-containers-with-podman-compose/[Manage containers with Podman Compose]